import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// import Layout from '../components/layout'
import News from '../components/news';
import CallToActionWithVideo from '../components/cta';
import Newsletter from '../components/newsletter';
import NewsPost from '../components/newsPost';
import Hero from '../components/hero';
import Testimony from '../components/testimonies';

export default function Home() {
  return (
  
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <News />
      <Hero />
      <CallToActionWithVideo />
      <NewsPost />
      {/* <Newsletter /> */}
      <Hero />
      <Testimony />
    </div>
  )
}
