import Head from 'next/head'
// import Image from 'next/image'

// import Layout from '../components/layout'
import NewsHeading from '../components/newsheading';
import CallToActionWithVideo from '../components/cta';
import Newsletter from '../components/newsletter';
import NewsAd from '../components/newsad';
import Hero from '../components/hero';
import Testimony from '../components/testimonies';
import NewsList from '../components/newslist';

export default function Home() {
  return (
  
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <NewsHeading />
      <NewsList header = "Today's news" />
      <Hero />
      <CallToActionWithVideo />
      <NewsAd />
      {/* <Newsletter /> */}
      <Hero />
      <Testimony />
    </div>
  )
}
